### ISSUE TITLE
Myaac v0.8.14 buttons error

### ISSUE THREAD

**Issue by ModernOTS** [slawkens/myaac#248]
### Server configuration
- Operating System: Ubuntu 20.04 LTS
- Web Server (+ version):  Apache/2.4.41
- PHP Version: v7.4.3-4ubuntu2.19
- Server name and version:  TFS 0.3
- MyAAC Version: Myaac v0.8.14

### Client configuration (Your Computer)

- Browser: tested in Firefox, Mircosoft Edge, Chrome(android)
- Operating System:  Windows 10, Android

### Description:
![obraz](https://github.com/slawkens/myaac/assets/155858437/183c6de2-651c-4d84-ae88-42253e17c983)

How to fix this?

**Comment by slawkens** [comment]
1) Did you try to clear cache in admin panel?

2) Thing that comes to my mind - you probably mean the buttons, right? Or do you mean other layout changes?

If you want to have original buttons like in tibiacom template, then you need to copy the files - templates/tibiacom/buttons.*.html.twig, but most importantly buttons.base.html.twig, because that's where the button code is saved.

**Comment by slawkens** [comment]
OK, no so I was wrong.

I managed do reproduce this - basically you are missing the ".BigButtonText" class in basic.css

**Comment by ModernOTS** [comment]
> OK, no so I was wrong.
> 
> I managed do reproduce this - basically you are missing the ".BigButtonText" class in basic

Thanks, that works.
